---
name: Hourly Renovate

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: Dry-Run
        default: false
        required: false
        type: boolean
      autoDiscover:
        description: Enable Repo Auto Discovery
        default: false
        required: false
        type: boolean
      autoDiscoverFilter:
        description: Repo Auto Discover Filter
        default: "*"
        required: false
        type: string
      logLevel:
        description: Log-Level
        default: debug
        required: false
        type: string
  schedule:
    - cron: "0 * * * *"

jobs:
  renovate:
    name: Renovate
    uses: mcfio/renovate-config/.github/workflows/renovate.yaml@main
    with:
      dryRun: ${{ inputs.dryRun || 'false' }}
      logLevel: ${{ inputs.logLevel || 'debug' }}
      autoDiscover: true
      autoDiscoverFilter: ${{ github.repository_owner }}/${{ inputs.autoDiscoverFilter || '*' }}
    secrets:
      app_id: ${{ secrets.BOT_APP_ID }}
      app_private_key: ${{ secrets.BOT_APP_PRIVATE_KEY }}

